### ISSUE TITLE
I have a problem signing up on my site

### ISSUE THREAD

**Issue by mm324** [cmd3BOT/Luminosity#2]
![image](https://user-images.githubusercontent.com/33562221/128624257-71ca0b0d-dec3-4dd9-92c5-b1b5fa03ecba.png)

no matter how many times i press the setup profile button on the sign up page, it does not move on

**Comment by cmd05** [comment]
Hi, It should be showing either an error for Invalid/Empty Email or Invalid Password thats why the screen must not be moving forward. ~~For me the page is moving forward on the site~~. If you are testing it on a cloned version try checking the response on the network tab, it could be a PHP error.

**Comment by cmd05** [comment]
Turns out the Email API had expired. Should be running now
