### ISSUE TITLE
How do I enter the admin panel?

### ISSUE THREAD

**Issue by paveell** [cmd3BOT/Luminosity#3]
Hello

How do I enter the admin panel?

Thank you!

**Comment by cmd05** [comment]
There is no "admin panel". However you can implement it yourself, using these [configs](https://github.com/cmd05/Luminosity/blob/main/application/Config/Config.example.php#L39-L40) and calling [`isAdmin()`](https://github.com/cmd05/Luminosity/blob/8290c57fcc63cb4a3cf2dfd3c4f854b90516be7c/application/Helpers/Server_helper.php#L57). 
An [example](https://github.com/cmd05/Luminosity/blob/main/application/Controllers/ViewControllers/Explore.php#L66)
